version: '2.1'

services:
  mfs:
    image: mfs
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - .:/usr/src/app
    command: node --inspect --harmony server